---
dataset:
  n_graphs: 100
  n_nodes: 100
  key: 0

model:
  hidden_dim: 32
  n_layers: 5
  key: 66

trainer:
  batch_size: 64
  evaluation_freq: 100
  evaluation_iters: 20
  learning_rate: 3e-4
  training_iters: 50000
  key: 42

wandb:
  entity: pierrotlc
  mode: ${..mode}

mode: offline

hydra:
  job:
    chdir: true
